export const users = [
  {
    firstName: "Mykola",
    lastName: "Serednii",
    email: "seredniimykola@gmail.com",
    phone: "476757575700",
    password: "$2b$10$jEcIk6rLurKd6kkAZNdJuOxoxLUrBHpD7N8w3hgw7BCjM7Ao3BHJK",
    role: "driver",
    license: "456356356356",
  },
  {
    firstName: "Ivan",
    lastName: "Kovalenko",
    email: "ivan.kovalenko@gmail.com",
    phone: "+380631234567",
    password: "$2b$10$XxUouP6eWvX5XNwd/pYHseVI6WBQXG6eEElDxUg1234567890qwerty",
    role: "driver",
    license: "A123456789",
  },
  {
    firstName: "Petro",
    lastName: "Tkachuk",
    email: "petro.tkachuk@gmail.com",
    phone: "+380987654321",
    password: "$2b$10$BqW9wn/NWtuV4uQyeXY13URZlkP1Mn78yXYcHOP0987654321asdfgh",
    role: "driver",
    license: "B987654321",
  },
  {
    firstName: "Andriy",
    lastName: "Shevchenko",
    email: "andriy.shevchenko@gmail.com",
    phone: "+38095123124567",
    password: "$2b$10$CkMn5heLOTViV6g9/UfhqAIO1BXGY78pqwrty567890lkjhgfdsazxc",
    role: "driver",
    license: "C345678901",
  },
  {
    firstName: "Oleh",
    lastName: "Yaroshenko",
    email: "oleh.yaroshenko@gmail.com",
    phone: "+3806711172233",
    password: "$2b$10$R4qKm8leOP34LfUIXz1cHQO67Wb98HgfTRed1234567890qazwsxedc",
    role: "driver",
    license: "D234567890",
  },
  {
    firstName: "Dmytro",
    lastName: "Bondarenko",
    email: "dmytro.bondarenko@gmail.com",
    phone: "+3809942233445",
    password: "$2b$10$LmNt5leIVYXw7rKGHTrFqJ78HfgT3UIm987654321mnbvcxzlkjhgfd",
    role: "driver",
    license: "E123098765",
  },
  {
    firstName: "Iryna",
    lastName: "Serednia",
    email: "seredniairyna@gmail.com",
    phone: "47675757576478",
    password: "$2b$10$vrxoOXOeF61ppkyhBaGEZ.rM1h8BhKX82LJW/os2TJ7pM3d64cby2",
    role: "driver",
    license: "456356356356",
  },
  {
    firstName: "Olena",
    lastName: "Burdiak",
    email: "olena.burdiak@lnu.edu.ua",
    phone: "+380687686339",
    password: "$2b$10$FG9ZKhPBLmfoqFSQdUpmEuAI/pohLuKI2FnwUuTdy8AfM5anmm/3G",
    role: "passenger",
    license: "no licens2154e",
  },
  {
    firstName: "test",
    lastName: "lastTest",
    email: "test@gmail.com",
    phone: "+321646546216486",
    password: "$2b$10$knR.6Y5Mhq876EKo.SsmLeW5enZ0olkwWNBSYmMchzx.e3EwbzhVy",
    role: "passenger",
    license: "00000000",
  },
  {
    firstName: "Oksana",
    lastName: "Ivanenko",
    email: "oksana.ivanenko@gmail.com",
    phone: "+380501234567",
    password: "$2b$10$a1b2c3d4e5f6g7h8i9j0klmnopqrstuvwxyz",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Iryna",
    lastName: "Kovalenko",
    email: "iryna.kovalenko@gmail.com",
    phone: "+38063123894567",
    password: "$2b$10$abcdefghijklmnopqrstuvwxyz1234567890",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Viktor",
    lastName: "Tkachuk",
    email: "viktor.tkachuk@gmail.com",
    phone: "+38098765114321",
    password: "$2b$10$fghijklmnopqrstuvwxyz1234567890abcdef",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Larysa",
    lastName: "Shevchenko",
    email: "larysa.shevchenko@gmail.com",
    phone: "+380951234567",
    password: "$2b$10$abcdefghijklmn7890opqrstuvwxyz123456",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Volodymyr",
    lastName: "Yaroshenko",
    email: "volodymyr.yaroshenko@gmail.com",
    phone: "+380671112233",
    password: "$2b$10$mnopqrstuvwx4567yzabcdefghi89012345",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Olha",
    lastName: "Bondarenko",
    email: "olha.bondarenko@gmail.com",
    phone: "+380992233445",
    password: "$2b$10$opqrstuvwxyz123456abcdefghi7890jklmn",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Roman",
    lastName: "Petruk",
    email: "roman.petruk@gmail.com",
    phone: "+380681112244",
    password: "$2b$10$qrstuvwxyzabcdefg1234567890hijklmn",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Daryna",
    lastName: "Skrypnyk",
    email: "daryna.skrypnyk@gmail.com",
    phone: "+380671234567",
    password: "$2b$10$ijklmnopqrstuvwxy7890zabcdefg12345",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Anatoliy",
    lastName: "Cherniak",
    email: "anatoliy.cherniak@gmail.com",
    phone: "+380501122334",
    password: "$2b$10$stuvwxyzabcdefghijklmno1234567890pq",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Svitlana",
    lastName: "Polishchuk",
    email: "svitlana.polishchuk@gmail.com",
    phone: "+380931112244",
    password: "$2b$10$klmnopqrstuvwxyzabcdefg1234567890hi",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Yaroslav",
    lastName: "Melnyk",
    email: "yaroslav.melnyk@gmail.com",
    phone: "+380671122334",
    password: "$2b$10$mnopqrstuvwxy1234567890zabcdefghijk",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Kateryna",
    lastName: "Bilyk",
    email: "kateryna.bilyk@gmail.com",
    phone: "+380631122334",
    password: "$2b$10$qrstuvwxyzabcdefghi7890jklmnopqrst",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Pavlo",
    lastName: "Hrytsenko",
    email: "pavlo.hrytsenko@gmail.com",
    phone: "+380681122334",
    password: "$2b$10$uvwxyzabcdefg1234567890hijklmnopqrs",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Myroslava",
    lastName: "Zhuk",
    email: "myroslava.zhuk@gmail.com",
    phone: "+380501234890",
    password: "$2b$10$1234567890qrstuvwxyzabcdefghijklmno",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Yurii",
    lastName: "Kravchenko",
    email: "yurii.kravchenko@gmail.com",
    phone: "+38067124534890",
    password: "$2b$10$abcdefg1234567890hijklmnopqrstuvwxy",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Nadia",
    lastName: "Kushnir",
    email: "nadia.kushnir@gmail.com",
    phone: "+380951112244",
    password: "$2b$10$ijklmnopqrstuvwx1234567890zabcdefgh",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Oleh",
    lastName: "Lyashenko",
    email: "oleh.lyashenko@gmail.com",
    phone: "+380681234890",
    password: "$2b$10$lmnopqrstuvwx4567yzabcdefghi8901234",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Alina",
    lastName: "Horobets",
    email: "alina.horobets@gmail.com",
    phone: "+380931234567",
    password: "$2b$10$mnopqrstuvwx1234567890zabcdefghijkl",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Ihor",
    lastName: "Stepanenko",
    email: "ihor.stepanenko@gmail.com",
    phone: "+380951112233",
    password: "$2b$10$mnopqrstuvwxyzabcdefg1234567890hijk",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Tetyana",
    lastName: "Marchenko",
    email: "tetyana.marchenko@gmail.com",
    phone: "+380671234890",
    password: "$2b$10$yzabcdefghi1234567890jklmnopqrstuvw",
    role: "passenger",
    license: "no license",
  },
];

export const routerDrivers = [
  {
    driverId: 5,
    departureDate: "2025-05-11T19:30:00.000Z",
    arrivalDate: "2025-01-11T19:00:00.000Z",
    departureFrom: "Houston",
    arrivalTo: "San Antonio",
    busNumber: "HOU-SA-2025",
    selectBusLayout: "1",
    routePrice: 25,
    maxSeats: 19,
    bookedSeats: 10,
    notate: "Economical and comfortable.",
    wifi: true,
    coffee: false,
    power: true,
    restRoom: false,
    modelBus: "Toyota Coaster",
    intermediateStops: ["Katy", "Sealy", "Columbus", "Flatonia", "Luling"],
    busSeats: [
      { number: 1, passenger: 1, busSeatStatus: "reserved" },
      { number: 2, passenger: null, busSeatStatus: "available" },
      { number: 3, passenger: 1, busSeatStatus: "reserved" },
      { number: 4, passenger: 1, busSeatStatus: "reserved" },
      { number: 5, passenger: null, busSeatStatus: "available" },
      { number: 6, passenger: 2, busSeatStatus: "reserved" },
      { number: 7, passenger: null, busSeatStatus: "available" },
      { number: 8, passenger: 2, busSeatStatus: "reserved" },
      { number: 9, passenger: null, busSeatStatus: "available" },
      { number: 10, passenger: null, busSeatStatus: "available" },
      { number: 11, passenger: 4, busSeatStatus: "reserved" },
      { number: 12, passenger: null, busSeatStatus: "available" },
      { number: 13, passenger: 6, busSeatStatus: "reserved" },
      { number: 14, passenger: null, busSeatStatus: "available" },
      { number: 15, passenger: 5, busSeatStatus: "reserved" },
      { number: 16, passenger: null, busSeatStatus: "available" },
      { number: 17, passenger: 4, busSeatStatus: "reserved" },
      { number: 18, passenger: null, busSeatStatus: "available" },
      { number: 19, passenger: 2, busSeatStatus: "reserved" },
    ],
    passengersSeatsList: [
      {
        idPassenger: 1,
        subPassengersLists: [
          {
            subFirstName: "",
            subLastName: "",
            subPhone: "",
            subEmail: "",
          },
        ],
      },
    ],
  },
  {
    driverId: 1,
    departureDate: "2025-05-11T19:30:00.000Z",
    arrivalDate: "2025-05-11T22:40:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "1",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 11,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",
    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      { number: 1, passenger: 1, busSeatStatus: "reserved" },
      { number: 2, passenger: null, busSeatStatus: "available" },
      { number: 3, passenger: 2, busSeatStatus: "reserved" },
      { number: 4, passenger: 3, busSeatStatus: "reserved" },
      { number: 5, passenger: null, busSeatStatus: "available" },
      { number: 6, passenger: 4, busSeatStatus: "reserved" },
      { number: 7, passenger: null, busSeatStatus: "available" },
      { number: 8, passenger: 5, busSeatStatus: "reserved" },
      { number: 9, passenger: null, busSeatStatus: "available" },
      { number: 10, passenger: null, busSeatStatus: "available" },
      { number: 11, passenger: 6, busSeatStatus: "reserved" },
      { number: 12, passenger: null, busSeatStatus: "available" },
      { number: 13, passenger: 7, busSeatStatus: "reserved" },
      { number: 14, passenger: 8, busSeatStatus: "available" },
      { number: 15, passenger: 9, busSeatStatus: "reserved" },
      { number: 16, passenger: null, busSeatStatus: "available" },
      { number: 17, passenger: 10, busSeatStatus: "reserved" },
      { number: 18, passenger: null, busSeatStatus: "available" },
      { number: 19, passenger: 11, busSeatStatus: "reserved" },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 2,
    departureDate: "2025-05-11T19:30:00.000Z",
    arrivalDate: "2025-05-11T22:40:00.000Z",
    departureFrom: "Miami",
    arrivalTo: "Orlando",
    busNumber: "MIA-ORL-2025",
    selectBusLayout: "2",
    routePrice: 35,
    maxSeats: 24,
    bookedSeats: 12,
    notate: "Short and sweet trip.",
    wifi: false,
    coffee: true,
    power: false,
    restRoom: true,
    modelBus: "Scania Touring",
    intermediateStops: ["Fort Lauderdale", "Palm Beach"],
    busSeats: [
      { number: 1, passenger: null, busSeatStatus: "available" },
      { number: 2, passenger: 12, busSeatStatus: "reserved" },
      { number: 3, passenger: 13, busSeatStatus: "reserved" },
      { number: 4, passenger: null, busSeatStatus: "available" },
      { number: 5, passenger: 14, busSeatStatus: "reserved" },
      { number: 6, passenger: null, busSeatStatus: "available" },
      { number: 7, passenger: null, busSeatStatus: "available" },
      { number: 8, passenger: 15, busSeatStatus: "reserved" },
      { number: 9, passenger: null, busSeatStatus: "available" },
      { number: 10, passenger: 16, busSeatStatus: "reserved" },
      { number: 11, passenger: null, busSeatStatus: "available" },
      { number: 12, passenger: 17, busSeatStatus: "reserved" },
      { number: 13, passenger: null, busSeatStatus: "available" },
      { number: 14, passenger: 18, busSeatStatus: "reserved" },
      { number: 15, passenger: null, busSeatStatus: "available" },
      { number: 16, passenger: null, busSeatStatus: "available" },
      { number: 17, passenger: 18, busSeatStatus: "reserved" },
      { number: 18, passenger: null, busSeatStatus: "available" },
      { number: 19, passenger: 19, busSeatStatus: "reserved" },
      { number: 20, passenger: null, busSeatStatus: "available" },
      { number: 21, passenger: 20, busSeatStatus: "reserved" },
      { number: 22, passenger: null, busSeatStatus: "available" },
      { number: 23, passenger: 20, busSeatStatus: "reserved" },
      { number: 24, passenger: 20, busSeatStatus: "reserved" },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 3,
    departureDate: "2025-05-12T08:00:00.000Z",
    arrivalDate: "2025-05-12T14:00:00.000Z",
    departureFrom: "Chicago",
    arrivalTo: "Detroit",
    busNumber: "CHI-DET-2025",
    selectBusLayout: "3",
    routePrice: 40,
    maxSeats: 29,
    bookedSeats: 14,
    notate: "Scenic views along the way.",
    wifi: true,
    coffee: false,
    power: true,
    restRoom: true,
    modelBus: "Mercedes Sprinter",
    intermediateStops: ["Gary", "Ann Arbor"],
    busSeats: [
      { number: 1, passenger: 1, busSeatStatus: "reserved" },
      { number: 2, passenger: null, busSeatStatus: "available" },
      { number: 3, passenger: null, busSeatStatus: "available" },
      { number: 4, passenger: 2, busSeatStatus: "reserved" },
      { number: 5, passenger: null, busSeatStatus: "available" },
      { number: 6, passenger: 2, busSeatStatus: "reserved" },
      { number: 7, passenger: 2, busSeatStatus: "reserved" },
      { number: 8, passenger: null, busSeatStatus: "available" },
      { number: 9, passenger: null, busSeatStatus: "available" },
      { number: 10, passenger: 3, busSeatStatus: "reserved" },
      { number: 11, passenger: 3, busSeatStatus: "reserved" },
      { number: 12, passenger: null, busSeatStatus: "available" },
      { number: 13, passenger: 4, busSeatStatus: "reserved" },
      { number: 14, passenger: null, busSeatStatus: "available" },
      { number: 15, passenger: 4, busSeatStatus: "reserved" },
      { number: 16, passenger: null, busSeatStatus: "available" },
      { number: 17, passenger: null, busSeatStatus: "available" },
      { number: 18, passenger: 5, busSeatStatus: "reserved" },
      { number: 19, passenger: null, busSeatStatus: "available" },
      { number: 20, passenger: null, busSeatStatus: "available" },
      { number: 21, passenger: 6, busSeatStatus: "reserved" },
      { number: 22, passenger: 6, busSeatStatus: "reserved" },
      { number: 23, passenger: null, busSeatStatus: "available" },
      { number: 24, passenger: 7, busSeatStatus: "reserved" },
      { number: 25, passenger: null, busSeatStatus: "available" },
      { number: 26, passenger: 8, busSeatStatus: "reserved" },
      { number: 27, passenger: null, busSeatStatus: "available" },
      { number: 28, passenger: 9, busSeatStatus: "reserved" },
      { number: 29, passenger: null, busSeatStatus: "available" },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 4,
    departureDate: "2025-05-13T12:40:00.000Z",
    arrivalDate: "2025-05-13T19:50:00.000Z",
    departureFrom: "Los Angeles",
    arrivalTo: "San Francisco",
    busNumber: "LA-SF-2025",
    selectBusLayout: "4",
    routePrice: 60,
    maxSeats: 35,
    bookedSeats: 16,
    notate: "Luxury travel with spacious seats.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Tesla Coach",
    intermediateStops: ["Santa Barbara", "San Jose"],
    busSeats: [
      { number: 1, passenger: 10, busSeatStatus: "reserved" },
      { number: 2, passenger: null, busSeatStatus: "available" },
      { number: 3, passenger: 11, busSeatStatus: "reserved" },
      { number: 4, passenger: null, busSeatStatus: "available" },
      { number: 5, passenger: 12, busSeatStatus: "reserved" },
      { number: 6, passenger: 12, busSeatStatus: "reserved" },
      { number: 7, passenger: null, busSeatStatus: "available" },
      { number: 8, passenger: null, busSeatStatus: "available" },
      { number: 9, passenger: 13, busSeatStatus: "reserved" },
      { number: 10, passenger: null, busSeatStatus: "available" },
      { number: 11, passenger: 14, busSeatStatus: "reserved" },
      { number: 12, passenger: null, busSeatStatus: "available" },
      { number: 13, passenger: 15, busSeatStatus: "reserved" },
      { number: 14, passenger: null, busSeatStatus: "available" },
      { number: 15, passenger: 15, busSeatStatus: "reserved" },
      { number: 16, passenger: null, busSeatStatus: "available" },
      { number: 17, passenger: null, busSeatStatus: "available" },
      { number: 18, passenger: 16, busSeatStatus: "reserved" },
      { number: 19, passenger: null, busSeatStatus: "available" },
      { number: 20, passenger: null, busSeatStatus: "available" },
      { number: 21, passenger: 17, busSeatStatus: "reserved" },
      { number: 22, passenger: null, busSeatStatus: "available" },
      { number: 23, passenger: 18, busSeatStatus: "reserved" },
      { number: 24, passenger: 18, busSeatStatus: "reserved" },
      { number: 25, passenger: null, busSeatStatus: "available" },
      { number: 26, passenger: 19, busSeatStatus: "reserved" },
      { number: 27, passenger: null, busSeatStatus: "available" },
      { number: 28, passenger: null, busSeatStatus: "available" },
      { number: 29, passenger: 19, busSeatStatus: "reserved" },
      { number: 30, passenger: null, busSeatStatus: "available" },
      { number: 31, passenger: 19, busSeatStatus: "reserved" },
      { number: 32, passenger: null, busSeatStatus: "available" },
      { number: 33, passenger: null, busSeatStatus: "available" },
      { number: 34, passenger: 20, busSeatStatus: "reserved" },
      { number: 35, passenger: null, busSeatStatus: "available" },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 5,
    departureDate: "2025-05-14T10:00:00.000Z",
    arrivalDate: "2025-05-14T14:00:00.000Z",
    departureFrom: "Seattle",
    arrivalTo: "Portland",
    busNumber: "SEA-PDX-2025",
    selectBusLayout: "5",
    routePrice: 30,
    maxSeats: 39,
    bookedSeats: 20,
    notate: "Comfortable trip with great amenities.",
    wifi: true,
    coffee: false,
    power: true,
    restRoom: true,
    modelBus: "Volvo XC60",
    intermediateStops: ["Olympia"],
    busSeats: [
      { number: 1, passenger: 1, busSeatStatus: "reserved" },
      { number: 2, passenger: null, busSeatStatus: "available" },
      { number: 3, passenger: 2, busSeatStatus: "reserved" },
      { number: 4, passenger: 3, busSeatStatus: "reserved" },
      { number: 5, passenger: null, busSeatStatus: "available" },
      { number: 6, passenger: 4, busSeatStatus: "reserved" },
      { number: 7, passenger: null, busSeatStatus: "available" },
      { number: 8, passenger: 4, busSeatStatus: "reserved" },
      { number: 9, passenger: null, busSeatStatus: "available" },
      { number: 10, passenger: null, busSeatStatus: "available" },
      { number: 11, passenger: 4, busSeatStatus: "reserved" },
      { number: 12, passenger: null, busSeatStatus: "available" },
      { number: 13, passenger: 5, busSeatStatus: "reserved" },
      { number: 14, passenger: 5, busSeatStatus: "reserved" },
      { number: 15, passenger: null, busSeatStatus: "available" },
      { number: 16, passenger: null, busSeatStatus: "available" },
      { number: 17, passenger: 5, busSeatStatus: "reserved" },
      { number: 18, passenger: null, busSeatStatus: "available" },
      { number: 19, passenger: null, busSeatStatus: "available" },
      { number: 20, passenger: 6, busSeatStatus: "reserved" },
      { number: 21, passenger: 6, busSeatStatus: "reserved" },
      { number: 22, passenger: null, busSeatStatus: "available" },
      { number: 23, passenger: 7, busSeatStatus: "reserved" },
      { number: 24, passenger: null, busSeatStatus: "available" },
      { number: 25, passenger: 8, busSeatStatus: "reserved" },
      { number: 26, passenger: 8, busSeatStatus: "reserved" },
      { number: 27, passenger: null, busSeatStatus: "available" },
      { number: 28, passenger: null, busSeatStatus: "available" },
      { number: 29, passenger: 9, busSeatStatus: "reserved" },
      { number: 30, passenger: null, busSeatStatus: "available" },
      { number: 31, passenger: 9, busSeatStatus: "reserved" },
      { number: 32, passenger: null, busSeatStatus: "available" },
      { number: 33, passenger: 10, busSeatStatus: "reserved" },
      { number: 34, passenger: null, busSeatStatus: "available" },
      { number: 35, passenger: 10, busSeatStatus: "reserved" },
      { number: 36, passenger: null, busSeatStatus: "available" },
      { number: 37, passenger: 11, busSeatStatus: "reserved" },
      { number: 38, passenger: 11, busSeatStatus: "reserved" },
      { number: 39, passenger: null, busSeatStatus: "available" },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 6,
    departureDate: "2025-05-15T16:00:00.000Z",
    arrivalDate: "2025-05-15T22:00:00.000Z",
    departureFrom: "Austin",
    arrivalTo: "Dallas",
    busNumber: "AUS-DAL-2025",
    selectBusLayout: "6",
    routePrice: 45,
    maxSeats: 47,
    bookedSeats: 23,
    notate: "Night journey with reclining seats.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Ford Transit",
    intermediateStops: ["Waco"],
    busSeats: [
      { number: 1, passenger: null, busSeatStatus: "available" },
      { number: 2, passenger: 12, busSeatStatus: "reserved" },
      { number: 3, passenger: null, busSeatStatus: "available" },
      { number: 4, passenger: 12, busSeatStatus: "reserved" },
      { number: 5, passenger: null, busSeatStatus: "available" },
      { number: 6, passenger: 13, busSeatStatus: "reserved" },
      { number: 7, passenger: null, busSeatStatus: "available" },
      { number: 8, passenger: null, busSeatStatus: "available" },
      { number: 9, passenger: 14, busSeatStatus: "reserved" },
      { number: 10, passenger: null, busSeatStatus: "available" },
      { number: 11, passenger: 14, busSeatStatus: "reserved" },
      { number: 12, passenger: null, busSeatStatus: "available" },
      { number: 13, passenger: 14, busSeatStatus: "reserved" },
      { number: 14, passenger: 14, busSeatStatus: "reserved" },
      { number: 15, passenger: null, busSeatStatus: "available" },
      { number: 16, passenger: null, busSeatStatus: "available" },
      { number: 17, passenger: 15, busSeatStatus: "reserved" },
      { number: 18, passenger: 15, busSeatStatus: "reserved" },
      { number: 19, passenger: null, busSeatStatus: "available" },
      { number: 20, passenger: null, busSeatStatus: "available" },
      { number: 21, passenger: 15, busSeatStatus: "reserved" },
      { number: 22, passenger: null, busSeatStatus: "available" },
      { number: 23, passenger: 16, busSeatStatus: "reserved" },
      { number: 24, passenger: null, busSeatStatus: "available" },
      { number: 25, passenger: 16, busSeatStatus: "reserved" },
      { number: 26, passenger: null, busSeatStatus: "available" },
      { number: 27, passenger: 16, busSeatStatus: "reserved" },
      { number: 28, passenger: null, busSeatStatus: "available" },
      { number: 29, passenger: 17, busSeatStatus: "reserved" },
      { number: 30, passenger: 17, busSeatStatus: "reserved" },
      { number: 31, passenger: null, busSeatStatus: "available" },
      { number: 32, passenger: null, busSeatStatus: "available" },
      { number: 33, passenger: 17, busSeatStatus: "reserved" },
      { number: 34, passenger: 17, busSeatStatus: "reserved" },
      { number: 35, passenger: null, busSeatStatus: "available" },
      { number: 36, passenger: null, busSeatStatus: "available" },
      { number: 37, passenger: 18, busSeatStatus: "reserved" },
      { number: 38, passenger: null, busSeatStatus: "available" },
      { number: 39, passenger: null, busSeatStatus: "available" },
      { number: 40, passenger: 18, busSeatStatus: "reserved" },
      { number: 41, passenger: 18, busSeatStatus: "reserved" },
      { number: 42, passenger: null, busSeatStatus: "available" },
      { number: 43, passenger: 19, busSeatStatus: "reserved" },
      { number: 44, passenger: null, busSeatStatus: "available" },
      { number: 45, passenger: 19, busSeatStatus: "reserved" },
      { number: 46, passenger: null, busSeatStatus: "available" },
      { number: 47, passenger: 20, busSeatStatus: "reserved" },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 5,
    departureDate: "2025-05-17T14:00:00.000Z",
    arrivalDate: "2025-05-17T19:00:00.000Z",
    departureFrom: "Houston",
    arrivalTo: "San Antonio",
    busNumber: "HOU-SA-2025",
    selectBusLayout: "1",
    routePrice: 25,
    maxSeats: 19,
    bookedSeats: 10,
    notate: "Economical and comfortable.",
    wifi: true,
    coffee: false,
    power: true,
    restRoom: false,
    modelBus: "Toyota Coaster",
    intermediateStops: [],
    busSeats: [
      { number: 1, passenger: 1, busSeatStatus: "reserved" },
      { number: 2, passenger: null, busSeatStatus: "available" },
      { number: 3, passenger: 1, busSeatStatus: "reserved" },
      { number: 4, passenger: 1, busSeatStatus: "reserved" },
      { number: 5, passenger: null, busSeatStatus: "available" },
      { number: 6, passenger: 2, busSeatStatus: "reserved" },
      { number: 7, passenger: null, busSeatStatus: "available" },
      { number: 8, passenger: 2, busSeatStatus: "reserved" },
      { number: 9, passenger: null, busSeatStatus: "available" },
      { number: 10, passenger: null, busSeatStatus: "available" },
      { number: 11, passenger: 4, busSeatStatus: "reserved" },
      { number: 12, passenger: null, busSeatStatus: "available" },
      { number: 13, passenger: 6, busSeatStatus: "reserved" },
      { number: 14, passenger: null, busSeatStatus: "available" },
      { number: 15, passenger: 5, busSeatStatus: "reserved" },
      { number: 16, passenger: null, busSeatStatus: "available" },
      { number: 17, passenger: 4, busSeatStatus: "reserved" },
      { number: 18, passenger: null, busSeatStatus: "available" },
      { number: 19, passenger: 2, busSeatStatus: "reserved" },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 5,
    departureDate: "2025-01-09T16:00:00.000Z",
    arrivalDate: "2025-05-10T22:00:00.000Z",
    departureFrom: "Austin",
    arrivalTo: "Dallas",
    busNumber: "AUS-DAL-2025",
    selectBusLayout: "6",
    routePrice: 45,
    maxSeats: 47,
    bookedSeats: 23,
    notate: "Night journey with reclining seats.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Ford Transit",
    intermediateStops: ["Waco"],
    busSeats: [
      { number: 1, passenger: null, busSeatStatus: "available" },
      { number: 2, passenger: 12, busSeatStatus: "reserved" },
      { number: 3, passenger: null, busSeatStatus: "available" },
      { number: 4, passenger: 12, busSeatStatus: "reserved" },
      { number: 5, passenger: null, busSeatStatus: "available" },
      { number: 6, passenger: 13, busSeatStatus: "reserved" },
      { number: 7, passenger: null, busSeatStatus: "available" },
      { number: 8, passenger: null, busSeatStatus: "available" },
      { number: 9, passenger: 14, busSeatStatus: "reserved" },
      { number: 10, passenger: null, busSeatStatus: "available" },
      { number: 11, passenger: 14, busSeatStatus: "reserved" },
      { number: 12, passenger: null, busSeatStatus: "available" },
      { number: 13, passenger: 14, busSeatStatus: "reserved" },
      { number: 14, passenger: 14, busSeatStatus: "reserved" },
      { number: 15, passenger: null, busSeatStatus: "available" },
      { number: 16, passenger: null, busSeatStatus: "available" },
      { number: 17, passenger: 15, busSeatStatus: "reserved" },
      { number: 18, passenger: 15, busSeatStatus: "reserved" },
      { number: 19, passenger: null, busSeatStatus: "available" },
      { number: 20, passenger: null, busSeatStatus: "available" },
      { number: 21, passenger: 15, busSeatStatus: "reserved" },
      { number: 22, passenger: null, busSeatStatus: "available" },
      { number: 23, passenger: 16, busSeatStatus: "reserved" },
      { number: 24, passenger: null, busSeatStatus: "available" },
      { number: 25, passenger: 16, busSeatStatus: "reserved" },
      { number: 26, passenger: null, busSeatStatus: "available" },
      { number: 27, passenger: 16, busSeatStatus: "reserved" },
      { number: 28, passenger: null, busSeatStatus: "available" },
      { number: 29, passenger: 17, busSeatStatus: "reserved" },
      { number: 30, passenger: 17, busSeatStatus: "reserved" },
      { number: 31, passenger: null, busSeatStatus: "available" },
      { number: 32, passenger: null, busSeatStatus: "available" },
      { number: 33, passenger: 17, busSeatStatus: "reserved" },
      { number: 34, passenger: 17, busSeatStatus: "reserved" },
      { number: 35, passenger: null, busSeatStatus: "available" },
      { number: 36, passenger: null, busSeatStatus: "available" },
      { number: 37, passenger: 18, busSeatStatus: "reserved" },
      { number: 38, passenger: null, busSeatStatus: "available" },
      { number: 39, passenger: null, busSeatStatus: "available" },
      { number: 40, passenger: 18, busSeatStatus: "reserved" },
      { number: 41, passenger: 18, busSeatStatus: "reserved" },
      { number: 42, passenger: null, busSeatStatus: "available" },
      { number: 43, passenger: 19, busSeatStatus: "reserved" },
      { number: 44, passenger: null, busSeatStatus: "available" },
      { number: 45, passenger: 19, busSeatStatus: "reserved" },
      { number: 46, passenger: null, busSeatStatus: "available" },
      { number: 47, passenger: 20, busSeatStatus: "reserved" },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 5,
    departureDate: "2025-05-20T10:00:00.000Z",
    arrivalDate: "2025-05-21T14:00:00.000Z",
    departureFrom: "Seattle",
    arrivalTo: "Portland",
    busNumber: "SEA-PDX-2025",
    selectBusLayout: "5",
    routePrice: 30,
    maxSeats: 39,
    bookedSeats: 20,
    notate: "Comfortable trip with great amenities.",
    wifi: true,
    coffee: false,
    power: true,
    restRoom: true,
    modelBus: "Volvo XC60",
    intermediateStops: ["Olympia"],
    busSeats: [
      { number: 1, passenger: 1, busSeatStatus: "reserved" },
      { number: 2, passenger: null, busSeatStatus: "available" },
      { number: 3, passenger: 2, busSeatStatus: "reserved" },
      { number: 4, passenger: 3, busSeatStatus: "reserved" },
      { number: 5, passenger: null, busSeatStatus: "available" },
      { number: 6, passenger: 4, busSeatStatus: "reserved" },
      { number: 7, passenger: null, busSeatStatus: "available" },
      { number: 8, passenger: 4, busSeatStatus: "reserved" },
      { number: 9, passenger: null, busSeatStatus: "available" },
      { number: 10, passenger: null, busSeatStatus: "available" },
      { number: 11, passenger: 4, busSeatStatus: "reserved" },
      { number: 12, passenger: null, busSeatStatus: "available" },
      { number: 13, passenger: 5, busSeatStatus: "reserved" },
      { number: 14, passenger: 5, busSeatStatus: "reserved" },
      { number: 15, passenger: null, busSeatStatus: "available" },
      { number: 16, passenger: null, busSeatStatus: "available" },
      { number: 17, passenger: 5, busSeatStatus: "reserved" },
      { number: 18, passenger: null, busSeatStatus: "available" },
      { number: 19, passenger: null, busSeatStatus: "available" },
      { number: 20, passenger: 6, busSeatStatus: "reserved" },
      { number: 21, passenger: 6, busSeatStatus: "reserved" },
      { number: 22, passenger: null, busSeatStatus: "available" },
      { number: 23, passenger: 7, busSeatStatus: "reserved" },
      { number: 24, passenger: null, busSeatStatus: "available" },
      { number: 25, passenger: 8, busSeatStatus: "reserved" },
      { number: 26, passenger: 8, busSeatStatus: "reserved" },
      { number: 27, passenger: null, busSeatStatus: "available" },
      { number: 28, passenger: null, busSeatStatus: "available" },
      { number: 29, passenger: 9, busSeatStatus: "reserved" },
      { number: 30, passenger: null, busSeatStatus: "available" },
      { number: 31, passenger: 9, busSeatStatus: "reserved" },
      { number: 32, passenger: null, busSeatStatus: "available" },
      { number: 33, passenger: 10, busSeatStatus: "reserved" },
      { number: 34, passenger: null, busSeatStatus: "available" },
      { number: 35, passenger: 10, busSeatStatus: "reserved" },
      { number: 36, passenger: null, busSeatStatus: "available" },
      { number: 37, passenger: 11, busSeatStatus: "reserved" },
      { number: 38, passenger: 11, busSeatStatus: "reserved" },
      { number: 39, passenger: null, busSeatStatus: "available" },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 1,
    departureDate: "2025-01-11T19:30:00.000Z",
    arrivalDate: "2025-01-11T22:40:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",
    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 1,
    departureDate: "2025-01-11T19:30:00.000Z",
    arrivalDate: "2025-01-11T22:40:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",
    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 1,
    departureDate: "2025-01-11T17:00:00.000Z",
    arrivalDate: "2025-01-11T23:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",
    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 1,
    departureDate: "2025-01-10T08:00:00.000Z",
    arrivalDate: "2025-01-10T12:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 1,
    departureDate: "2025-01-11T18:10:00.000Z",
    arrivalDate: "2025-01-12T12:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 1,
    departureDate: "2025-01-15T15:30:00.000Z",
    arrivalDate: "2025-01-16T16:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 1,
    departureDate: "2025-01-12T13:00:00.000Z",
    arrivalDate: "2025-01-14T12:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 1,
    departureDate: "2025-01-14T03:00:00.000Z",
    arrivalDate: "2025-01-15T06:20:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 1,
    departureDate: "2025-01-14T08:00:00.000Z",
    arrivalDate: "2025-01-15T03:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 1,
    departureDate: "2025-01-12T09:00:00.000Z",
    arrivalDate: "2025-01-15T12:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 1,
    departureDate: "2025-01-13T12:00:00.000Z",
    arrivalDate: "2025-01-13T22:40:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 1,
    departureDate: "2025-01-08T08:00:00.000Z",
    arrivalDate: "2025-01-09T12:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 1,
    departureDate: "2025-01-09T09:09:00.000Z",
    arrivalDate: "2025-01-09T12:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 1,
    departureDate: "2025-01-08T08:50:00.000Z",
    arrivalDate: "2025-01-10T12:45:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",
    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 1,
    departureDate: "2025-01-07T08:00:00.000Z",
    arrivalDate: "2025-01-08T14:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 1,
    departureDate: "2025-01-10T09:06:00.000Z",
    arrivalDate: "2025-01-11T12:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 1,
    departureDate: "2025-01-10T22:00:00.000Z",
    arrivalDate: "2025-01-11T18:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
    passengersSeatsList: [],
  },
  {
    driverId: 1,
    departureDate: "2025-01-01T07:30:00.000Z",
    arrivalDate: "2025-01-01T12:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",
    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
    passengersSeatsList: [],
  },
];
