export const users = [
  {
    firstName: "Mykola",
    lastName: "Serednii",
    email: "seredniimykola@gmail.com",
    phone: "476757575700",
    password: "$2b$10$jEcIk6rLurKd6kkAZNdJuOxoxLUrBHpD7N8w3hgw7BCjM7Ao3BHJK",
    role: "driver",
    license: "456356356356",
  },
  {
    firstName: "Ivan",
    lastName: "Kovalenko",
    email: "ivan.kovalenko@gmail.com",
    phone: "+380631234567",
    password: "$2b$10$XxUouP6eWvX5XNwd/pYHseVI6WBQXG6eEElDxUg1234567890qwerty",
    role: "driver",
    license: "A123456789",
  },
  {
    firstName: "Petro",
    lastName: "Tkachuk",
    email: "petro.tkachuk@gmail.com",
    phone: "+380987654321",
    password: "$2b$10$BqW9wn/NWtuV4uQyeXY13URZlkP1Mn78yXYcHOP0987654321asdfgh",
    role: "driver",
    license: "B987654321",
  },
  {
    firstName: "Andriy",
    lastName: "Shevchenko",
    email: "andriy.shevchenko@gmail.com",
    phone: "+38095123124567",
    password: "$2b$10$CkMn5heLOTViV6g9/UfhqAIO1BXGY78pqwrty567890lkjhgfdsazxc",
    role: "driver",
    license: "C345678901",
  },
  {
    firstName: "Oleh",
    lastName: "Yaroshenko",
    email: "oleh.yaroshenko@gmail.com",
    phone: "+3806711172233",
    password: "$2b$10$R4qKm8leOP34LfUIXz1cHQO67Wb98HgfTRed1234567890qazwsxedc",
    role: "driver",
    license: "D234567890",
  },
  {
    firstName: "Dmytro",
    lastName: "Bondarenko",
    email: "dmytro.bondarenko@gmail.com",
    phone: "+3809942233445",
    password: "$2b$10$LmNt5leIVYXw7rKGHTrFqJ78HfgT3UIm987654321mnbvcxzlkjhgfd",
    role: "driver",
    license: "E123098765",
  },
  {
    firstName: "Iryna",
    lastName: "Serednia",
    email: "seredniairyna@gmail.com",
    phone: "47675757576478",
    password: "$2b$10$vrxoOXOeF61ppkyhBaGEZ.rM1h8BhKX82LJW/os2TJ7pM3d64cby2",
    role: "driver",
    license: "456356356356",
  },
  {
    firstName: "Olena",
    lastName: "Burdiak",
    email: "olena.burdiak@lnu.edu.ua",
    phone: "+380687686339",
    password: "$2b$10$FG9ZKhPBLmfoqFSQdUpmEuAI/pohLuKI2FnwUuTdy8AfM5anmm/3G",
    role: "passenger",
    license: "no licens2154e",
  },
  {
    firstName: "test",
    lastName: "lastTest",
    email: "test@gmail.com",
    phone: "+321646546216486",
    password: "$2b$10$knR.6Y5Mhq876EKo.SsmLeW5enZ0olkwWNBSYmMchzx.e3EwbzhVy",
    role: "passenger",
    license: "00000000",
  },
  {
    firstName: "Oksana",
    lastName: "Ivanenko",
    email: "oksana.ivanenko@gmail.com",
    phone: "+380501234567",
    password: "$2b$10$a1b2c3d4e5f6g7h8i9j0klmnopqrstuvwxyz",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Iryna",
    lastName: "Kovalenko",
    email: "iryna.kovalenko@gmail.com",
    phone: "+38063123894567",
    password: "$2b$10$abcdefghijklmnopqrstuvwxyz1234567890",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Viktor",
    lastName: "Tkachuk",
    email: "viktor.tkachuk@gmail.com",
    phone: "+38098765114321",
    password: "$2b$10$fghijklmnopqrstuvwxyz1234567890abcdef",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Larysa",
    lastName: "Shevchenko",
    email: "larysa.shevchenko@gmail.com",
    phone: "+380951234567",
    password: "$2b$10$abcdefghijklmn7890opqrstuvwxyz123456",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Volodymyr",
    lastName: "Yaroshenko",
    email: "volodymyr.yaroshenko@gmail.com",
    phone: "+380671112233",
    password: "$2b$10$mnopqrstuvwx4567yzabcdefghi89012345",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Olha",
    lastName: "Bondarenko",
    email: "olha.bondarenko@gmail.com",
    phone: "+380992233445",
    password: "$2b$10$opqrstuvwxyz123456abcdefghi7890jklmn",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Roman",
    lastName: "Petruk",
    email: "roman.petruk@gmail.com",
    phone: "+380681112244",
    password: "$2b$10$qrstuvwxyzabcdefg1234567890hijklmn",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Daryna",
    lastName: "Skrypnyk",
    email: "daryna.skrypnyk@gmail.com",
    phone: "+380671234567",
    password: "$2b$10$ijklmnopqrstuvwxy7890zabcdefg12345",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Anatoliy",
    lastName: "Cherniak",
    email: "anatoliy.cherniak@gmail.com",
    phone: "+380501122334",
    password: "$2b$10$stuvwxyzabcdefghijklmno1234567890pq",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Svitlana",
    lastName: "Polishchuk",
    email: "svitlana.polishchuk@gmail.com",
    phone: "+380931112244",
    password: "$2b$10$klmnopqrstuvwxyzabcdefg1234567890hi",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Yaroslav",
    lastName: "Melnyk",
    email: "yaroslav.melnyk@gmail.com",
    phone: "+380671122334",
    password: "$2b$10$mnopqrstuvwxy1234567890zabcdefghijk",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Kateryna",
    lastName: "Bilyk",
    email: "kateryna.bilyk@gmail.com",
    phone: "+380631122334",
    password: "$2b$10$qrstuvwxyzabcdefghi7890jklmnopqrst",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Pavlo",
    lastName: "Hrytsenko",
    email: "pavlo.hrytsenko@gmail.com",
    phone: "+380681122334",
    password: "$2b$10$uvwxyzabcdefg1234567890hijklmnopqrs",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Myroslava",
    lastName: "Zhuk",
    email: "myroslava.zhuk@gmail.com",
    phone: "+380501234890",
    password: "$2b$10$1234567890qrstuvwxyzabcdefghijklmno",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Yurii",
    lastName: "Kravchenko",
    email: "yurii.kravchenko@gmail.com",
    phone: "+38067124534890",
    password: "$2b$10$abcdefg1234567890hijklmnopqrstuvwxy",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Nadia",
    lastName: "Kushnir",
    email: "nadia.kushnir@gmail.com",
    phone: "+380951112244",
    password: "$2b$10$ijklmnopqrstuvwx1234567890zabcdefgh",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Oleh",
    lastName: "Lyashenko",
    email: "oleh.lyashenko@gmail.com",
    phone: "+380681234890",
    password: "$2b$10$lmnopqrstuvwx4567yzabcdefghi8901234",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Alina",
    lastName: "Horobets",
    email: "alina.horobets@gmail.com",
    phone: "+380931234567",
    password: "$2b$10$mnopqrstuvwx1234567890zabcdefghijkl",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Ihor",
    lastName: "Stepanenko",
    email: "ihor.stepanenko@gmail.com",
    phone: "+380951112233",
    password: "$2b$10$mnopqrstuvwxyzabcdefg1234567890hijk",
    role: "passenger",
    license: "no license",
  },
  {
    firstName: "Tetyana",
    lastName: "Marchenko",
    email: "tetyana.marchenko@gmail.com",
    phone: "+380671234890",
    password: "$2b$10$yzabcdefghi1234567890jklmnopqrstuvw",
    role: "passenger",
    license: "no license",
  },
];

export const routerDrivers = [
  {
    driverId: 5,
    departureDate: "2025-05-11T19:30:00.000Z",
    arrivalDate: "2025-01-11T19:00:00.000Z",
    departureFrom: "Houston",
    arrivalTo: "San Antonio",
    busNumber: "HOU-SA-2025",
    selectBusLayout: "1",
    routePrice: 25,
    maxSeats: 19,
    bookedSeats: 10,
    notate: "Economical and comfortable.",
    wifi: true,
    coffee: false,
    power: true,
    restRoom: false,
    modelBus: "Toyota Coaster",
    intermediateStops: ["Katy", "Sealy", "Columbus", "Flatonia", "Luling"],
    busSeats: [
      { number: 1, passenger: 1, busSeatStatus: "reserved" },
      { number: 2, passenger: null, busSeatStatus: "available" },
      { number: 3, passenger: 1, busSeatStatus: "reserved" },
      { number: 4, passenger: 1, busSeatStatus: "reserved" },
      { number: 5, passenger: null, busSeatStatus: "available" },
      { number: 6, passenger: 2, busSeatStatus: "reserved" },
      { number: 7, passenger: null, busSeatStatus: "available" },
      { number: 8, passenger: 2, busSeatStatus: "reserved" },
      { number: 9, passenger: null, busSeatStatus: "available" },
      { number: 10, passenger: null, busSeatStatus: "available" },
      { number: 11, passenger: 4, busSeatStatus: "reserved" },
      { number: 12, passenger: null, busSeatStatus: "available" },
      { number: 13, passenger: 6, busSeatStatus: "reserved" },
      { number: 14, passenger: null, busSeatStatus: "available" },
      { number: 15, passenger: 5, busSeatStatus: "reserved" },
      { number: 16, passenger: null, busSeatStatus: "available" },
      { number: 17, passenger: 4, busSeatStatus: "reserved" },
      { number: 18, passenger: null, busSeatStatus: "available" },
      { number: 19, passenger: 2, busSeatStatus: "reserved" },
    ],
    // passengersSeatsList: [
    //   {
    //     idPassenger: 1,
    //     subPassengersList: [
    //       {
    //         subFirstName: "srsdrgs",
    //         subLastName: "wserytsrtywrty",
    //         subPhone: "wertwertwert",
    //         subEmail: "wertwrtwrt",
    //       },
    //     ],
    //   },
    // ],
  },
  // {
  //   driverId: 1,
  //   departureDate: "2025-05-11T19:30:00.000Z",
  //   arrivalDate: "2025-05-11T22:40:00.000Z",
  //   departureFrom: "New York",
  //   arrivalTo: "Washington, D.C.",
  //   busNumber: "NY-WDC-2025",
  //   selectBusLayout: "1",
  //   routePrice: 50,
  //   maxSeats: 19,
  //   bookedSeats: 11,
  //   notate: "This is a comfortable route.",
  //   wifi: true,
  //   coffee: true,
  //   power: true,
  //   restRoom: true,
  //   modelBus: "Volvo 240",
  //   intermediateStops: ["Philadelphia", "Baltimore"],
  //   busSeats: [
  //     { number: 1, passenger: 1, busSeatStatus: "reserved" },
  //     { number: 2, passenger: null, busSeatStatus: "available" },
  //     { number: 3, passenger: 2, busSeatStatus: "reserved" },
  //     { number: 4, passenger: 3, busSeatStatus: "reserved" },
  //     { number: 5, passenger: null, busSeatStatus: "available" },
  //     { number: 6, passenger: 4, busSeatStatus: "reserved" },
  //     { number: 7, passenger: null, busSeatStatus: "available" },
  //     { number: 8, passenger: 5, busSeatStatus: "reserved" },
  //     { number: 9, passenger: null, busSeatStatus: "available" },
  //     { number: 10, passenger: null, busSeatStatus: "available" },
  //     { number: 11, passenger: 6, busSeatStatus: "reserved" },
  //     { number: 12, passenger: null, busSeatStatus: "available" },
  //     { number: 13, passenger: 7, busSeatStatus: "reserved" },
  //     { number: 14, passenger: 8, busSeatStatus: "available" },
  //     { number: 15, passenger: 9, busSeatStatus: "reserved" },
  //     { number: 16, passenger: null, busSeatStatus: "available" },
  //     { number: 17, passenger: 10, busSeatStatus: "reserved" },
  //     { number: 18, passenger: null, busSeatStatus: "available" },
  //     { number: 19, passenger: 11, busSeatStatus: "reserved" },
  //   ],
  //   passengersSeatsList: [],
  // },
];
