export const users = [
  {
    firstName: "BOHDAN",
    lastName: "ILCHYSHYN",
    email: "bogdan@pcgramota.ru",
    phone: "345336674764",
    password: "$2b$10$/SByyfUPZ.61i4N8U8cyg.h71ZSc97q8BDQ8W2JNnABNMOZvo0c2y",
    role: "driver",
    license: "3453563456",
  },
  {
    firstName: "Olena",
    lastName: "Burdiak",
    email: "olena.burdiak@lnu.edu.ua",
    phone: "+38068768656339",
    password: "$2b$10$FG9ZKhPBLmfoqFSQdUpmEuAI/pohLuKI2FnwUuTdy8AfM5anmm/3G",
    role: "passenger",
    license: "no licens2154e",
  },
  {
    firstName: "test",
    lastName: "lastTest",
    email: "test@pcgramota.ru",
    phone: "+321646546216486",
    password: "$2b$10$knR.6Y5Mhq876EKo.SsmLeW5enZ0olkwWNBSYmMchzx.e3EwbzhVy",
    role: "passenger",
    license: "passenjukiyikljger",
  },
  {
    firstName: "Serednii",
    lastName: "Mykola",
    email: "seredniimykola1@gmail.com",
    phone: "4767575757226",
    password: "$2b$10$jEcIk6rLurKd6kkAZNdJuOxoxLUrBHpD7N8w3hgw7BCjM7Ao3BHJK",
    role: "driver",
    license: "456356356356",
  },

  {
    firstName: "Serednii",
    lastName: "Mykola",
    email: "seredniimykdgola5@gmail.com",
    phone: "47675734557575654",
    password: "$2b$10$vrxoOXOeF61ppkyhBaGEZ.rM1h8BhKX82LJW/os2TJ7pM3d64cby2",
    role: "driver",
    license: "456356356356",
  },
  {
    firstName: "BOHDAN",
    lastName: "ILCHYSHYN",
    email: "bogdan45@pcgramota.ru",
    phone: "34533456674764",
    password: "$2b$10$/SByyfUPZ.61i4N8U8cyg.h71ZSc97q8BDQ8W2JNnABNMOZvo0c2y",
    role: "driver",
    license: "3453563456",
  },
  {
    firstName: "Olena",
    lastName: "Burdiak",
    email: "olena.bu45rdiak@lnu.edu.ua",
    phone: "+38065687686339",
    password: "$2b$10$FG9ZKhPBLmfoqFSQdUpmEuAI/pohLuKI2FnwUuTdy8AfM5anmm/3G",
    role: "passenger",
    license: "no licens2154e",
  },
  {
    firstName: "test",
    lastName: "lastTest",
    email: "tes456t@pcgramota.ru",
    phone: "+321456646546216486",
    password: "$2b$10$knR.6Y5Mhq876EKo.SsmLeW5enZ0olkwWNBSYmMchzx.e3EwbzhVy",
    role: "passenger",
    license: "passenjukiyikljger",
  },
  {
    firstName: "Serednii",
    lastName: "Mykola",
    email: "seredn456iimykola1@gmail.com",
    phone: "47675734665757",
    password: "$2b$10$jEcIk6rLurKd6kkAZNdJuOxoxLUrBHpD7N8w3hgw7BCjM7Ao3BHJK",
    role: "driver",
    license: "456356356356",
  },
  {
    firstName: "Serednii",
    lastName: "Mykola",
    email: "sered456niimykola5@gmail.com",
    phone: "476754536757576",
    password: "$2b$10$vrxoOXOeF61ppkyhBaGEZ.rM1h8BhKX82LJW/os2TJ7pM3d64cby2",
    role: "driver",
    license: "456356356356",
  },

  {
    firstName: "Olena",
    lastName: "Burdiak",
    email: "olena.bu45rdidfhdghdak@lnu.edu.ua",
    phone: "+38065645687686339",
    password: "$2b$10$FG9ZKhPBLmfoqFSQdUpmEuAI/pohLuKI2FnwUuTdy8AfM5anmm/3G",
    role: "passenger",
    license: "no licens2154e",
  },
  {
    firstName: "test",
    lastName: "lastTest",
    email: "tesww6456t@pcgramota.ru",
    phone: "+321478956646546216486",
    password: "$2b$10$knR.6Y5Mhq876EKo.SsmLeW5enZ0olkwWNBSYmMchzx.e3EwbzhVy",
    role: "passenger",
    license: "passenjukiyikljger",
  },
  {
    firstName: "Serednii",
    lastName: "Mykola",
    email: "seredn456ii456mykola1@gmail.com",
    phone: "47675555734665757",
    password: "$2b$10$jEcIk6rLurKd6kkAZNdJuOxoxLUrBHpD7N8w3hgw7BCjM7Ao3BHJK",
    role: "driver",
    license: "456356356356",
  },
  {
    firstName: "Serednii",
    lastName: "Mykola",
    email: "sered5645456niimykola5@gmail.com",
    phone: "476745654536757576",
    password: "$2b$10$vrxoOXOeF61ppkyhBaGEZ.rM1h8BhKX82LJW/os2TJ7pM3d64cby2",
    role: "driver",
    license: "456356356356",
  },
];

export const routerDrivers = [
  {
    driverId: 1,
    departureDate: "2025-01-11T19:30:00.000Z",
    arrivalDate: "2025-01-11T22:40:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",
    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
  },
  {
    driverId: 1,
    departureDate: "2025-01-11T19:30:00.000Z",
    arrivalDate: "2025-01-11T22:40:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",
    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
  },
  {
    driverId: 1,
    departureDate: "2025-01-11T17:00:00.000Z",
    arrivalDate: "2025-01-11T23:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",
    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
  },
  {
    driverId: 1,
    departureDate: "2025-01-10T08:00:00.000Z",
    arrivalDate: "2025-01-10T12:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
  },
  {
    driverId: 1,
    departureDate: "2025-01-11T18:10:00.000Z",
    arrivalDate: "2025-01-12T12:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
  },
  {
    driverId: 1,
    departureDate: "2025-01-15T15:30:00.000Z",
    arrivalDate: "2025-01-16T16:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
  },
  {
    driverId: 1,
    departureDate: "2025-01-12T13:00:00.000Z",
    arrivalDate: "2025-01-14T12:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
  },
  {
    driverId: 1,
    departureDate: "2025-01-14T03:00:00.000Z",
    arrivalDate: "2025-01-15T06:20:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
  },
  {
    driverId: 1,
    departureDate: "2025-01-14T08:00:00.000Z",
    arrivalDate: "2025-01-15T03:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
  },
  {
    driverId: 1,
    departureDate: "2025-01-12T09:00:00.000Z",
    arrivalDate: "2025-01-15T12:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
  },
  {
    driverId: 1,
    departureDate: "2025-01-13T12:00:00.000Z",
    arrivalDate: "2025-01-13T22:40:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
  },
  {
    driverId: 1,
    departureDate: "2025-01-08T08:00:00.000Z",
    arrivalDate: "2025-01-09T12:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
  },
  {
    driverId: 1,
    departureDate: "2025-01-09T09:09:00.000Z",
    arrivalDate: "2025-01-09T12:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
  },
  {
    driverId: 1,
    departureDate: "2025-01-08T08:50:00.000Z",
    arrivalDate: "2025-01-10T12:45:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",
    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
  },
  {
    driverId: 1,
    departureDate: "2025-01-07T08:00:00.000Z",
    arrivalDate: "2025-01-08T14:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
  },
  {
    driverId: 1,
    departureDate: "2025-01-10T09:06:00.000Z",
    arrivalDate: "2025-01-11T12:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
  },
  {
    driverId: 1,
    departureDate: "2025-01-10T22:00:00.000Z",
    arrivalDate: "2025-01-11T18:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",

    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
  },
  {
    driverId: 1,
    departureDate: "2025-01-01T07:30:00.000Z",
    arrivalDate: "2025-01-01T12:00:00.000Z",
    departureFrom: "New York",
    arrivalTo: "Washington, D.C.",
    busNumber: "NY-WDC-2025",
    selectBusLayout: "2",
    routePrice: 50,
    maxSeats: 19,
    bookedSeats: 6,
    notate: "This is a comfortable route.",
    wifi: true,
    coffee: true,
    power: true,
    restRoom: true,
    modelBus: "Volvo 240",
    intermediateStops: ["Philadelphia", "Baltimore"],
    busSeats: [
      {
        number: 1,
        passenger: 1,
        busSeatStatus: "reserved",
      },
      {
        number: 5,
        passenger: 2,
        busSeatStatus: "reserved",
      },
      {
        number: 8,
        passenger: 5,
        busSeatStatus: "reserved",
      },
      {
        number: 11,
        passenger: 8,
        busSeatStatus: "reserved",
      },
      {
        number: 14,
        passenger: 10,
        busSeatStatus: "reserved",
      },
      {
        number: 2,
        passenger: 11,
        busSeatStatus: "reserved",
      },
      {
        number: 6,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 9,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 12,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 15,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 3,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 7,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 10,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 13,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 16,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 4,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 19,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 18,
        passenger: null,
        busSeatStatus: "available",
      },
      {
        number: 17,
        passenger: null,
        busSeatStatus: "available",
      },
    ],
  },
];
