import { SeatStatusEnum } from "@/enum/shared.enums";
import { ILayoutData } from "@/types/layoutbus.types";

export const layoutsData: ILayoutData[] = [
  {
    passengerLength: 19,
    busWidth: "570px",
    busHeight: "200px",
    modelBus: "Bus 1",
    driverSeat: {
      left: "80px",
      bottom: "20px",
    },
    stairs: [
      {
        left: "150px",
        top: "0",
      },
    ],
    passenger: [
      {
        left: 150,
        bottom: 5,
        number: 1,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        bottom: 5,
        number: 5,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        bottom: 5,
        number: 8,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        bottom: 5,
        number: 11,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        bottom: 5,
        number: 14,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 150,
        bottom: 48,
        number: 2,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        bottom: 48,
        number: 6,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        bottom: 48,
        number: 9,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        bottom: 48,
        number: 12,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        bottom: 48,
        number: 15,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 50,
        top: 5,
        number: 3,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        top: 5,
        number: 7,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        top: 5,
        number: 10,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        top: 5,
        number: 13,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        top: 5,
        number: 16,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 50,
        top: 48,
        number: 4,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        right: 5,
        top: 5,
        number: 19,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 108,
        number: 18,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 151,
        number: 17,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
    ],
  },

  {
    passengerLength: 24,
    modelBus: "Bus 2",
    busWidth: "570px",
    busHeight: "230px",
    driverSeat: {
      left: "80px",
      bottom: "20px",
    },
    stairs: [
      {
        left: "150px",
        top: "0",
      },
    ],
    passenger: [
      {
        left: 150,
        bottom: 5,
        number: 1,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        bottom: 5,
        number: 5,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        bottom: 5,
        number: 9,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        bottom: 5,
        number: 13,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        bottom: 5,
        number: 17,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 150,
        bottom: 48,
        number: 2,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        bottom: 48,
        number: 6,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        bottom: 48,
        number: 10,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        bottom: 48,
        number: 14,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        bottom: 48,
        number: 18,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 50,
        top: 5,
        number: 3,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        top: 5,
        number: 7,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        top: 5,
        number: 11,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        top: 5,
        number: 15,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        top: 5,
        number: 19,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 50,
        top: 48,
        number: 4,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        top: 48,
        number: 8,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        top: 48,
        number: 12,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        top: 48,
        number: 16,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        top: 48,
        number: 20,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        right: 5,
        top: 5,
        number: 24,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 48,
        number: 23,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 135,
        number: 22,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 178,
        number: 21,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
    ],
  },

  {
    passengerLength: 29,
    modelBus: "Bus 3",
    busWidth: "710px",
    busHeight: "230px",
    driverSeat: {
      left: "80px",
      bottom: "20px",
    },
    stairs: [
      {
        left: "50px",
        top: "0",
      },
      {
        left: "500px",
        top: "0",
      },
    ],
    passenger: [
      {
        left: 150,
        top: 5,
        number: 3,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        top: 5,
        number: 7,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        top: 5,
        number: 11,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        top: 5,
        number: 15,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        top: 5,
        number: 19,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 150,
        top: 48,
        number: 4,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        top: 48,
        number: 8,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        top: 48,
        number: 12,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        top: 48,
        number: 16,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        top: 48,
        number: 20,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 150,
        bottom: 48,
        number: 2,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        bottom: 48,
        number: 6,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        bottom: 48,
        number: 10,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        bottom: 48,
        number: 14,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        bottom: 48,
        number: 18,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 500,
        bottom: 48,
        number: 22,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 570,
        bottom: 48,
        number: 24,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 150,
        bottom: 5,
        number: 1,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        bottom: 5,
        number: 5,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        bottom: 5,
        number: 9,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        bottom: 5,
        number: 13,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        bottom: 5,
        number: 17,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 500,
        bottom: 5,
        number: 21,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 570,
        bottom: 5,
        number: 23,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        right: 5,
        top: 5,
        number: 29,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 48,
        number: 28,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 92,
        number: 27,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 135,
        number: 26,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 178,
        number: 25,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
    ],
  },

  {
    passengerLength: 35,
    modelBus: "Bus 4",
    busWidth: "800px",
    busHeight: "230px",
    driverSeat: {
      left: "80px",
      bottom: "20px",
    },
    stairs: [
      {
        left: "50px",
        top: "0",
      },
      {
        left: "650px",
        top: "0",
      },
    ],
    passenger: [
      {
        left: 150,
        top: 5,
        number: 3,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        top: 5,
        number: 7,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        top: 5,
        number: 11,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        top: 5,
        number: 15,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        top: 5,
        number: 19,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 500,
        top: 5,
        number: 23,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 570,
        top: 5,
        number: 27,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 150,
        top: 48,
        number: 4,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        top: 48,
        number: 8,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        top: 48,
        number: 12,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        top: 48,
        number: 16,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        top: 48,
        number: 20,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 500,
        top: 48,
        number: 24,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 570,
        top: 48,
        number: 28,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 150,
        bottom: 48,
        number: 2,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        bottom: 48,
        number: 6,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        bottom: 48,
        number: 10,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        bottom: 48,
        number: 14,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        bottom: 48,
        number: 18,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 500,
        bottom: 48,
        number: 22,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 570,
        bottom: 48,
        number: 26,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 640,
        bottom: 48,
        number: 30,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 150,
        bottom: 5,
        number: 1,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        bottom: 5,
        number: 5,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        bottom: 5,
        number: 9,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        bottom: 5,
        number: 13,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        bottom: 5,
        number: 17,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 500,
        bottom: 5,
        number: 21,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 570,
        bottom: 5,
        number: 25,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 640,
        bottom: 5,
        number: 29,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        right: 5,
        top: 5,
        number: 35,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 48,
        number: 34,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 92,
        number: 33,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 135,
        number: 32,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 178,
        number: 31,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
    ],
  },

  {
    passengerLength: 39,
    modelBus: "Bus 5",
    busWidth: "860px",
    busHeight: "230px",
    driverSeat: {
      left: "80px",
      bottom: "20px",
    },
    stairs: [
      {
        left: "50px",
        top: "0",
      },
      {
        left: "430px",
        top: "0",
      },
    ],
    passenger: [
      {
        left: 150,
        top: 5,
        number: 3,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        top: 5,
        number: 7,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        top: 5,
        number: 11,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        top: 5,
        number: 15,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 500,
        top: 5,
        number: 22,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 570,
        top: 5,
        number: 26,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 640,
        top: 5,
        number: 30,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 710,
        top: 5,
        number: 34,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 150,
        top: 48,
        number: 4,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        top: 48,
        number: 8,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        top: 48,
        number: 12,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        top: 48,
        number: 16,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 500,
        top: 48,
        number: 21,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 570,
        top: 48,
        number: 25,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 640,
        top: 48,
        number: 29,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 710,
        top: 48,
        number: 33,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 150,
        bottom: 48,
        number: 2,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        bottom: 48,
        number: 6,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        bottom: 48,
        number: 10,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        bottom: 48,
        number: 14,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        bottom: 48,
        number: 18,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 500,
        bottom: 48,
        number: 20,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 570,
        bottom: 48,
        number: 24,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 640,
        bottom: 48,
        number: 28,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 710,
        bottom: 48,
        number: 32,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 150,
        bottom: 5,
        number: 1,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        bottom: 5,
        number: 5,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        bottom: 5,
        number: 9,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        bottom: 5,
        number: 13,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        bottom: 5,
        number: 17,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 500,
        bottom: 5,
        number: 19,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 570,
        bottom: 5,
        number: 23,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 640,
        bottom: 5,
        number: 27,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 710,
        bottom: 5,
        number: 31,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        right: 5,
        top: 5,
        number: 39,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 48,
        number: 38,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 92,
        number: 37,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 135,
        number: 36,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 178,
        number: 35,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
    ],
  },

  {
    passengerLength: 47,
    modelBus: "Bus 6",
    busWidth: "1000px",
    busHeight: "230px",
    driverSeat: {
      left: "80px",
      bottom: "20px",
    },
    stairs: [
      {
        left: "50px",
        top: "0",
      },
      {
        right: "100px",
        top: "0",
      },
    ],
    passenger: [
      {
        left: 150,
        bottom: 5,
        number: 1,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        bottom: 5,
        number: 5,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        bottom: 5,
        number: 9,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        bottom: 5,
        number: 13,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        bottom: 5,
        number: 17,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 500,
        bottom: 5,
        number: 21,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 570,
        bottom: 5,
        number: 25,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 640,
        bottom: 5,
        number: 29,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 710,
        bottom: 5,
        number: 33,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 780,
        bottom: 5,
        number: 37,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 850,
        bottom: 5,
        number: 41,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 150,
        bottom: 48,
        number: 2,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        bottom: 48,
        number: 6,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        bottom: 48,
        number: 10,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        bottom: 48,
        number: 14,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        bottom: 48,
        number: 18,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 500,
        bottom: 48,
        number: 22,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 570,
        bottom: 48,
        number: 26,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 640,
        bottom: 48,
        number: 30,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 710,
        bottom: 48,
        number: 34,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 780,
        bottom: 48,
        number: 38,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 850,
        bottom: 48,
        number: 42,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 150,
        top: 5,
        number: 3,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        top: 5,
        number: 7,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        top: 5,
        number: 11,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        top: 5,
        number: 15,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        top: 5,
        number: 19,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 500,
        top: 5,
        number: 23,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 570,
        top: 5,
        number: 27,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 640,
        top: 5,
        number: 31,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 710,
        top: 5,
        number: 35,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 780,
        top: 5,
        number: 39,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        left: 150,
        top: 48,
        number: 4,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 220,
        top: 48,
        number: 8,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 290,
        top: 48,
        number: 12,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 360,
        top: 48,
        number: 16,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 430,
        top: 48,
        number: 20,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 500,
        top: 48,
        number: 24,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 570,
        top: 48,
        number: 28,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 640,
        top: 48,
        number: 32,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 710,
        top: 48,
        number: 36,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        left: 780,
        top: 48,
        number: 40,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },

      {
        right: 5,
        top: 5,
        number: 47,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 48,
        number: 46,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 92,
        number: 45,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 135,
        number: 44,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
      {
        right: 5,
        top: 178,
        number: 43,
        passenger: null,
        busSeatStatus: SeatStatusEnum.AVAILABLE,
      },
    ],
  },
];
