import { ILayoutData } from "./interface";
export const layoutsData: ILayoutData[] = [
  {
    passengerLength: 19,
    busWidth: "570px",
    busHeight: "200px",
    driverSeat: {
      left: "80px",
      bottom: "20px",
    },
    stairs: [
      {
        left: "150px",
        top: "0",
      },
    ],
    passenger: [
      { left: 150, bottom: 5, number: 1, busSeatStatus: "reserved" },
      { left: 220, bottom: 5, number: 5, busSeatStatus: "available" },
      { left: 290, bottom: 5, number: 8, busSeatStatus: "available" },
      { left: 360, bottom: 5, number: 11, busSeatStatus: "available" },
      { left: 430, bottom: 5, number: 14, busSeatStatus: "available" },

      { left: 150, bottom: 48, number: 2, busSeatStatus: "available" },
      { left: 220, bottom: 48, number: 6, busSeatStatus: "available" },
      { left: 290, bottom: 48, number: 9, busSeatStatus: "available" },
      { left: 360, bottom: 48, number: 12, busSeatStatus: "available" },
      { left: 430, bottom: 48, number: 15, busSeatStatus: "available" },

      { left: 50, top: 5, number: 3, busSeatStatus: "available" },
      { left: 220, top: 5, number: 7, busSeatStatus: "available" },
      { left: 290, top: 5, number: 10, busSeatStatus: "available" },
      { left: 360, top: 5, number: 13, busSeatStatus: "available" },
      { left: 430, top: 5, number: 16, busSeatStatus: "available" },

      { left: 50, top: 48, number: 4, busSeatStatus: "available" },

      { right: 5, top: 5, number: 19, busSeatStatus: "available" },
      { right: 5, top: 108, number: 18, busSeatStatus: "available" },
      { right: 5, top: 151, number: 17, busSeatStatus: "available" },
    ],
  },

  {
    passengerLength: 24,
    busWidth: "570px",
    busHeight: "230px",
    driverSeat: {
      left: "80px",
      bottom: "20px",
    },
    stairs: [
      {
        left: "150px",
        top: "0",
      },
    ],
    passenger: [
      { left: 150, bottom: 5, number: 1, busSeatStatus: "reserved" },
      { left: 220, bottom: 5, number: 5, busSeatStatus: "available" },
      { left: 290, bottom: 5, number: 9, busSeatStatus: "available" },
      { left: 360, bottom: 5, number: 13, busSeatStatus: "available" },
      { left: 430, bottom: 5, number: 17, busSeatStatus: "available" },

      { left: 150, bottom: 48, number: 2, busSeatStatus: "available" },
      { left: 220, bottom: 48, number: 6, busSeatStatus: "available" },
      { left: 290, bottom: 48, number: 10, busSeatStatus: "available" },
      { left: 360, bottom: 48, number: 14, busSeatStatus: "available" },
      { left: 430, bottom: 48, number: 18, busSeatStatus: "available" },

      { left: 50, top: 5, number: 3, busSeatStatus: "available" },
      { left: 220, top: 5, number: 7, busSeatStatus: "available" },
      { left: 290, top: 5, number: 11, busSeatStatus: "available" },
      { left: 360, top: 5, number: 15, busSeatStatus: "available" },
      { left: 430, top: 5, number: 19, busSeatStatus: "available" },

      { left: 50, top: 48, number: 4, busSeatStatus: "available" },
      { left: 220, top: 48, number: 8, busSeatStatus: "available" },
      { left: 290, top: 48, number: 12, busSeatStatus: "available" },
      { left: 360, top: 48, number: 16, busSeatStatus: "available" },
      { left: 430, top: 48, number: 20, busSeatStatus: "available" },

      { right: 5, top: 5, number: 24, busSeatStatus: "available" },
      { right: 5, top: 48, number: 23, busSeatStatus: "available" },
      { right: 5, top: 135, number: 22, busSeatStatus: "available" },
      { right: 5, top: 178, number: 21, busSeatStatus: "available" },
    ],
  },

  {
    passengerLength: 29,
    busWidth: "710px",
    busHeight: "230px",
    driverSeat: {
      left: "80px",
      bottom: "20px",
    },
    stairs: [
      {
        left: "50px",
        top: "0",
      },
      {
        left: "500px",
        top: "0",
      },
    ],
    passenger: [
      { left: 150, top: 5, number: 3, busSeatStatus: "available" },
      { left: 220, top: 5, number: 7, busSeatStatus: "available" },
      { left: 290, top: 5, number: 11, busSeatStatus: "available" },
      { left: 360, top: 5, number: 15, busSeatStatus: "available" },
      { left: 430, top: 5, number: 19, busSeatStatus: "available" },

      { left: 150, top: 48, number: 4, busSeatStatus: "available" },
      { left: 220, top: 48, number: 8, busSeatStatus: "available" },
      { left: 290, top: 48, number: 12, busSeatStatus: "available" },
      { left: 360, top: 48, number: 16, busSeatStatus: "available" },
      { left: 430, top: 48, number: 20, busSeatStatus: "available" },

      { left: 150, bottom: 48, number: 2, busSeatStatus: "available" },
      { left: 220, bottom: 48, number: 6, busSeatStatus: "available" },
      { left: 290, bottom: 48, number: 10, busSeatStatus: "available" },
      { left: 360, bottom: 48, number: 14, busSeatStatus: "available" },
      { left: 430, bottom: 48, number: 18, busSeatStatus: "available" },
      { left: 500, bottom: 48, number: 22, busSeatStatus: "available" },
      { left: 570, bottom: 48, number: 24, busSeatStatus: "available" },

      { left: 150, bottom: 5, number: 1, busSeatStatus: "reserved" },
      { left: 220, bottom: 5, number: 5, busSeatStatus: "available" },
      { left: 290, bottom: 5, number: 9, busSeatStatus: "available" },
      { left: 360, bottom: 5, number: 13, busSeatStatus: "available" },
      { left: 430, bottom: 5, number: 17, busSeatStatus: "available" },
      { left: 500, bottom: 5, number: 21, busSeatStatus: "available" },
      { left: 570, bottom: 5, number: 23, busSeatStatus: "available" },

      { right: 5, top: 5, number: 29, busSeatStatus: "available" },
      { right: 5, top: 48, number: 28, busSeatStatus: "available" },
      { right: 5, top: 92, number: 27, busSeatStatus: "available" },
      { right: 5, top: 135, number: 26, busSeatStatus: "available" },
      { right: 5, top: 178, number: 25, busSeatStatus: "available" },
    ],
  },

  {
    passengerLength: 35,
    busWidth: "800px",
    busHeight: "230px",
    driverSeat: {
      left: "80px",
      bottom: "20px",
    },
    stairs: [
      {
        left: "50px",
        top: "0",
      },
      {
        left: "650px",
        top: "0",
      },
    ],
    passenger: [
      { left: 150, top: 5, number: 3, busSeatStatus: "available" },
      { left: 220, top: 5, number: 7, busSeatStatus: "available" },
      { left: 290, top: 5, number: 11, busSeatStatus: "available" },
      { left: 360, top: 5, number: 15, busSeatStatus: "available" },
      { left: 430, top: 5, number: 19, busSeatStatus: "available" },
      { left: 500, top: 5, number: 23, busSeatStatus: "available" },
      { left: 570, top: 5, number: 27, busSeatStatus: "available" },

      { left: 150, top: 48, number: 4, busSeatStatus: "available" },
      { left: 220, top: 48, number: 8, busSeatStatus: "available" },
      { left: 290, top: 48, number: 12, busSeatStatus: "available" },
      { left: 360, top: 48, number: 16, busSeatStatus: "available" },
      { left: 430, top: 48, number: 20, busSeatStatus: "available" },
      { left: 500, top: 48, number: 24, busSeatStatus: "available" },
      { left: 570, top: 48, number: 28, busSeatStatus: "available" },

      { left: 150, bottom: 48, number: 2, busSeatStatus: "available" },
      { left: 220, bottom: 48, number: 6, busSeatStatus: "available" },
      { left: 290, bottom: 48, number: 10, busSeatStatus: "available" },
      { left: 360, bottom: 48, number: 14, busSeatStatus: "available" },
      { left: 430, bottom: 48, number: 18, busSeatStatus: "available" },
      { left: 500, bottom: 48, number: 22, busSeatStatus: "available" },
      { left: 570, bottom: 48, number: 26, busSeatStatus: "available" },
      { left: 640, bottom: 48, number: 30, busSeatStatus: "available" },

      { left: 150, bottom: 5, number: 1, busSeatStatus: "reserved" },
      { left: 220, bottom: 5, number: 5, busSeatStatus: "available" },
      { left: 290, bottom: 5, number: 9, busSeatStatus: "available" },
      { left: 360, bottom: 5, number: 13, busSeatStatus: "available" },
      { left: 430, bottom: 5, number: 17, busSeatStatus: "available" },
      { left: 500, bottom: 5, number: 21, busSeatStatus: "available" },
      { left: 570, bottom: 5, number: 25, busSeatStatus: "available" },
      { left: 640, bottom: 5, number: 29, busSeatStatus: "available" },

      { right: 5, top: 5, number: 35, busSeatStatus: "available" },
      { right: 5, top: 48, number: 34, busSeatStatus: "available" },
      { right: 5, top: 92, number: 33, busSeatStatus: "available" },
      { right: 5, top: 135, number: 32, busSeatStatus: "available" },
      { right: 5, top: 178, number: 31, busSeatStatus: "available" },
    ],
  },

  {
    passengerLength: 39,
    busWidth: "860px",
    busHeight: "230px",
    driverSeat: {
      left: "80px",
      bottom: "20px",
    },
    stairs: [
      {
        left: "50px",
        top: "0",
      },
      {
        left: "430px",
        top: "0",
      },
    ],
    passenger: [
      { left: 150, top: 5, number: 3, busSeatStatus: "available" },
      { left: 220, top: 5, number: 7, busSeatStatus: "available" },
      { left: 290, top: 5, number: 11, busSeatStatus: "available" },
      { left: 360, top: 5, number: 15, busSeatStatus: "available" },

      { left: 500, top: 5, number: 22, busSeatStatus: "available" },
      { left: 570, top: 5, number: 26, busSeatStatus: "available" },
      { left: 640, top: 5, number: 30, busSeatStatus: "available" },
      { left: 710, top: 5, number: 34, busSeatStatus: "available" },

      { left: 150, top: 48, number: 4, busSeatStatus: "available" },
      { left: 220, top: 48, number: 8, busSeatStatus: "available" },
      { left: 290, top: 48, number: 12, busSeatStatus: "available" },
      { left: 360, top: 48, number: 16, busSeatStatus: "available" },
      { left: 500, top: 48, number: 21, busSeatStatus: "available" },
      { left: 570, top: 48, number: 25, busSeatStatus: "available" },
      { left: 640, top: 48, number: 29, busSeatStatus: "available" },
      { left: 710, top: 48, number: 33, busSeatStatus: "available" },

      { left: 150, bottom: 48, number: 2, busSeatStatus: "available" },
      { left: 220, bottom: 48, number: 6, busSeatStatus: "available" },
      { left: 290, bottom: 48, number: 10, busSeatStatus: "available" },
      { left: 360, bottom: 48, number: 14, busSeatStatus: "available" },
      { left: 430, bottom: 48, number: 18, busSeatStatus: "available" },
      { left: 500, bottom: 48, number: 20, busSeatStatus: "available" },
      { left: 570, bottom: 48, number: 24, busSeatStatus: "available" },
      { left: 640, bottom: 48, number: 28, busSeatStatus: "available" },
      { left: 710, bottom: 48, number: 32, busSeatStatus: "available" },

      { left: 150, bottom: 5, number: 1, busSeatStatus: "reserved" },
      { left: 220, bottom: 5, number: 5, busSeatStatus: "available" },
      { left: 290, bottom: 5, number: 9, busSeatStatus: "available" },
      { left: 360, bottom: 5, number: 13, busSeatStatus: "available" },
      { left: 430, bottom: 5, number: 17, busSeatStatus: "available" },
      { left: 500, bottom: 5, number: 19, busSeatStatus: "available" },
      { left: 570, bottom: 5, number: 23, busSeatStatus: "available" },
      { left: 640, bottom: 5, number: 27, busSeatStatus: "available" },
      { left: 710, bottom: 5, number: 31, busSeatStatus: "available" },

      { right: 5, top: 5, number: 39, busSeatStatus: "available" },
      { right: 5, top: 48, number: 38, busSeatStatus: "available" },
      { right: 5, top: 92, number: 37, busSeatStatus: "available" },
      { right: 5, top: 135, number: 36, busSeatStatus: "available" },
      { right: 5, top: 178, number: 35, busSeatStatus: "available" },
    ],
  },

  {
    passengerLength: 47,
    busWidth: "1000px",
    busHeight: "230px",
    driverSeat: {
      left: "80px",
      bottom: "20px",
    },
    stairs: [
      {
        left: "50px",
        top: "0",
      },
      {
        right: "100px",
        top: "0",
      },
    ],
    passenger: [
      { left: 150, bottom: 5, number: 1, busSeatStatus: "reserved" },
      { left: 220, bottom: 5, number: 5, busSeatStatus: "available" },
      { left: 290, bottom: 5, number: 9, busSeatStatus: "available" },
      { left: 360, bottom: 5, number: 13, busSeatStatus: "available" },
      { left: 430, bottom: 5, number: 17, busSeatStatus: "available" },
      { left: 500, bottom: 5, number: 21, busSeatStatus: "available" },
      { left: 570, bottom: 5, number: 25, busSeatStatus: "available" },
      { left: 640, bottom: 5, number: 29, busSeatStatus: "available" },
      { left: 710, bottom: 5, number: 33, busSeatStatus: "available" },
      { left: 780, bottom: 5, number: 37, busSeatStatus: "available" },
      { left: 850, bottom: 5, number: 41, busSeatStatus: "available" },

      { left: 150, bottom: 48, number: 2, busSeatStatus: "available" },
      { left: 220, bottom: 48, number: 6, busSeatStatus: "available" },
      { left: 290, bottom: 48, number: 10, busSeatStatus: "available" },
      { left: 360, bottom: 48, number: 14, busSeatStatus: "available" },
      { left: 430, bottom: 48, number: 18, busSeatStatus: "available" },
      { left: 500, bottom: 48, number: 22, busSeatStatus: "available" },
      { left: 570, bottom: 48, number: 26, busSeatStatus: "available" },
      { left: 640, bottom: 48, number: 30, busSeatStatus: "available" },
      { left: 710, bottom: 48, number: 34, busSeatStatus: "available" },
      { left: 780, bottom: 48, number: 38, busSeatStatus: "available" },
      { left: 850, bottom: 48, number: 42, busSeatStatus: "available" },

      { left: 150, top: 5, number: 3, busSeatStatus: "available" },
      { left: 220, top: 5, number: 7, busSeatStatus: "available" },
      { left: 290, top: 5, number: 11, busSeatStatus: "available" },
      { left: 360, top: 5, number: 15, busSeatStatus: "available" },
      { left: 430, top: 5, number: 19, busSeatStatus: "available" },
      { left: 500, top: 5, number: 23, busSeatStatus: "available" },
      { left: 570, top: 5, number: 27, busSeatStatus: "available" },
      { left: 640, top: 5, number: 31, busSeatStatus: "available" },
      { left: 710, top: 5, number: 35, busSeatStatus: "available" },
      { left: 780, top: 5, number: 39, busSeatStatus: "available" },

      { left: 150, top: 48, number: 4, busSeatStatus: "available" },
      { left: 220, top: 48, number: 8, busSeatStatus: "available" },
      { left: 290, top: 48, number: 12, busSeatStatus: "available" },
      { left: 360, top: 48, number: 16, busSeatStatus: "available" },
      { left: 430, top: 48, number: 20, busSeatStatus: "available" },
      { left: 500, top: 48, number: 24, busSeatStatus: "available" },
      { left: 570, top: 48, number: 28, busSeatStatus: "available" },
      { left: 640, top: 48, number: 32, busSeatStatus: "available" },
      { left: 710, top: 48, number: 36, busSeatStatus: "available" },
      { left: 780, top: 48, number: 40, busSeatStatus: "available" },

      { right: 5, top: 5, number: 47, busSeatStatus: "available" },
      { right: 5, top: 48, number: 46, busSeatStatus: "available" },
      { right: 5, top: 92, number: 45, busSeatStatus: "available" },
      { right: 5, top: 135, number: 44, busSeatStatus: "available" },
      { right: 5, top: 178, number: 43, busSeatStatus: "available" },
    ],
  },
];
